name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
     
      - name: Publish Extensions Nuget Package
        id: publish_nuget_extensions
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: src/FaceitSharp/FaceitSharp.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}